### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by rffrasca** [rffrasca/PDFKeeper#23]
### Discussed in https://github.com/rffrasca/PDFKeeper/discussions/22

<div type='discussions-op-text'>

<sup>Originally posted by **rffrasca** December 24, 2023</sup>
When attempting to upload one or more PDF's that is missing a title, author, or subject; an unhandled exception is being thrown after the PDF's are copied into the top level of the **Upload** folder. Normally, when a PDF is missing a title, author, or subject; PDFKeeper is supposed to move the PDF to the **UploadRejected** folder. Unfortunately, because PDFKeeper has crashed, the PDF's will remain in the **Upload** folder causing the same unhandled exception to be thrown when PDFKeeper attempts to upload again after restarting.

Both PDFKeeper v9.0.0 and v9.1.0 are impacted by this bug.

**The stack trace of exception that is logged to PDFKeeper.log**
System.NullReferenceException: Object reference not set to an instance of an object.
   at PDFKeeper.Core.Rules.PdfMetadataRule.CheckForViolation()
   at PDFKeeper.Core.FileIO.PDF.PdfUploader.StagePdfFilesInUploadDirectory()
   at PDFKeeper.Core.Presenters.MainPresenter.ExecuteUpload()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PDFKeeper.Presentation.MainView.VB$StateMachine_491_UploadTimer_Tick.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

To prevent PDFKeeper from crashing again after restarting; move the PDF's out of **C:\Users\your_username\AppData\Roaming\Robert F. Frasca\PDFKeeper\Upload** and then restart PDFKeeper.</div>

**Comment by rffrasca** [comment]
PDFKeeper 9.1.1 was released today.
