### ISSUE TITLE
Export: System.IO.DirectoryNotFoundException: Could not find a part of the path.

### ISSUE THREAD

**Issue by rffrasca** [rffrasca/PDFKeeper#50]
**Describe the bug**
When a PDF is being exported for a selected document. a System.IO.DirectoryNotFoundException is being thrown when the length of the directory path name being created to store PDF and extra metadata is > 259 characters resulting in that document not being exported.

**To Reproduce**
1. Select documents to export in Documents list
2. Click File menu and then Export
3. Select target folder
4. Click OK
5. See error

**Expected behavior**
PDF document and extra metadata for each selected documents should be exported into the selected folder as <Author>\<Subject>\Title.pdf.

**Desktop (please complete the following information):**
OS: Windows 10 22H2
PDFKeeper Version: 11.0.0 and lower

**Additional context**
System.IO.DirectoryNotFoundException: Could not find a part of the path '<DIR_PATH_REDACTED>'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at PDFKeeper.Core.Commands.ExportDocumentCommand.Execute()
   at PDFKeeper.Core.Presenters.MainPresenter.ProcessEachCheckedDocument(CheckedDocumentAction checkedDocumentAction, String value)
   at PDFKeeper.Core.Presenters.MainPresenter.ExportEachSelectedDocument()
   at PDFKeeper.WinForms.Views.MainForm.ToolStripItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by rffrasca** [comment]
See #54
